name: njangi_app
description: "A premium fintech Njangi (rotating savings group) management application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  go_router:
  flutter_riverpod:
  google_fonts:
  flutter_svg:
  intl:
  pinput:
  country_code_picker:
  form_builder_validators:
  animations:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/icons/
  #   - assets/images/
